### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by rummyr** [lucascoelhof/ESP32BleAdvertise#2]
Looks like it is going to leak memory every time a new advertise is set..
        .p_manufacturer_data = (uint8_t *) malloc(data.length()*sizeof(uint8_t)),  //manufacturer data is what we will use to broadcast our info

**Comment by lucascoelhof** [comment]
@rummyr Will check that today!

**Comment by lucascoelhof** [comment]
Yes @rummyr  you are right, there is a memory leak. I used ESP.getFreeHeap() to get the available RAM and this is the result. You can clearly see that the RAM is reducing over time:

143828
143808
143796
143776
143764
143736
143724
143712
143700
143688
143676
143664
143652
143640
143628
143616

**Comment by lucascoelhof** [comment]
@rummyr Fixed it! Thanks for opening the issue. I forgot to close the issue on the commit message, but please see my last commit.
